### ISSUE TITLE
Convert unicode to latex

### ISSUE THREAD

**Issue by lenhard** [tomtung/latex2unicode#2]
Hi Tom,

This is just an idea for a feature. How about supporting the reverse direction for the conversion in this library: From unicode text to LaTeX-escaped text? 

Since you have the maps for LaTeX to unicode conversion, it might be possible to support the reverse direction without too much effort (I hope). We need this conversion in JabRef as well and would be glad to rely on latex2unicode!

If you are not interested in implementing this you can just close the issue.

Regards
Jörg

**Comment by tomtung** [comment]
Hmm having the mapping is only part of the solution; coming up with a good grammar for parsing can also be tricky. I haven't thought it through, but to reach the same coverage as LaTex->Unicode can be non-trivial. I'll think more about it, but please don’t hold your breath :)
