### ISSUE TITLE
Haskell port

### ISSUE THREAD

**Issue by Quelklef** [tomtung/latex2unicode#22]
Hey there!

Recently I did a little survey of existing "latex to unicode" converters. As far as I can tell, `latex2unicode` is by far the best out there, due to genuinely parsing the input instead of doing a naive find-and-replace.

As such, I really wanted to use it, but for irrelevant details can't really use Scala on my system. The result ... I've created a Haskell port! It's like to diverge from `latex2unicode`, but at the very least the first commit is a roughly one-to-one port.

Wanted to drop a comment here and say:

1. Thanks for the fabulous work

2. [Here's](https://github.com/Quelklef/latuc) the port, in case this is useful info to anyone

Cheers =)

**Comment by tomtung** [comment]
Thanks, glad you found it useful :)
