### ISSUE TITLE
Incorrect display of LaTeX string with TeX commands

### ISSUE THREAD

**Issue by spontaneous-emission** [tomtung/latex2unicode#3]
This issue is related to the use of latex2unicode in the JabRef project and hence is possibly beyond the scope of this project. (issue https://github.com/JabRef/jabref/issues/2651)

Author strings that contain special characters (such as Č) in citations exported by APS journals include some TeX code `\ifmmode ... \else .. \fi{}` so that the entry will display correctly if the environment is math mode or normal. For example:
`author = {\ifmmode \check{C}\else \v{C}\fi{}ernot\'{\i}k, Ond\ifmmode \check{r}\else \v{r}\fi{}ej and Hammerer, Klemens}`

Using the online demo of latex2unicode (which uses version 0.2 of latex2unicode) and also the development version of JabRef, which, as far as I can tell, uses the latest version of latex2unicode, this does not show up correctly, producing two copies of each of the special characters rather than one, e.g. `Č Černotı́k, Ond ř řej and Hammerer, Klemens` when this should be: `Černotı́k, Ondřej and Hammerer, Klemens`.

**Comment by tomtung** [comment]
Yeah handling if conditions is currently out of the scope... let me know if you have some quick fixes in mind :)
