### ISSUE TITLE
Captial letters after an underscore are wrapped in braces

### ISSUE THREAD

**Issue by Siedlerchr** [tomtung/latex2unicode#4]
Hi,

first all thanks for the great lib ;)
while using JabRef I noticed one problem using the formatter: **https://github.com/JabRef/jabref/issues/2664**

Have a string  `Underscore_Underscore`
when running the formatter, I get `Underscore_(U)nderscore`

Regards
Christoph

**Comment by Siedlerchr** [comment]
I have thought a bit about this issue and would propose the idea to only recognize it as latex if there is either exactly one letter or number following, or better only recognize it as latex if after the underscore curly braces follow. Otherwise ignore treat it directly as latex-free string.

**Comment by tomtung** [comment]
Hmm I think the behavior of determining subscript is consistent with latex (although if not in the math environment a compile error would be thrown). In other words, I guess latex2unicode is doing its job as intended?

Maybe JabRef can add some extra logic to determine when latex2unicode should kick in?

**Comment by koppor** [comment]
I don't get, why braces (`(` and `)`)  are added around the letter. This is no unicode, is it?

**Comment by koppor** [comment]
Maybe, subscript and superscript should be implemented using the unicode characters? https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts#Latin_and_Greek_tables

**Comment by tomtung** [comment]
Yeah so only some characters have corresponding Unicode subscripts and superscripts. For those that don't, I used `_(whatever)` to denote that they should actually be subscripts.

**Comment by koppor** [comment]
We have huge issue with my proposal. A roundtrip is not possible any more. I am currently not sure whether it its JabRef or this library. I recorded the issue at JabRef's side at https://github.com/JabRef/jabref/issues/3644.
